#---- CONSTANTS ----#
# Teams IDs
TEAM_A1 = b"pipA1"
TEAM_A2 = b"pipB1"
TEAM_B1 = b"pipB2"
TEAM_B2 = b"pipA2"
TEAM_C1 = b"pipC1"
TEAM_C2 = b"pipC2"
BROADCAST_ID = b"Bcast"

FOLDERPATH="/home/pi/NM_Folder"
#USB_PATH="/media/usb"
FILE_NAME = "/NM.txt"


MY_PIPE_ID = TEAM_C1

TIMEOUT = 10
BACK_OFF_TIME = 2
BACK_OFF_COUNT = 10
TRANSMIT_ATTEMPTS = 5
CHANNEL1 = 90
CHANNEL2 = 97

FILE_REQUEST_RANDOM_WAIT = 10
REQUEST_ACC_RANDOM_WAIT = 5

FILE_REQUEST_MSG = b"FileRequestMsg"
REQUEST_ACC_MSG = b"RequestAccMsg"
TRANSMIT_ACC_MSG = b"TransmitAccMsg"